### ISSUE TITLE
Attempts per solve can be rounded to 2 decimal places. 

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#1001]
![image](https://user-images.githubusercontent.com/26947311/65172128-0a4c8700-da7f-11e9-855d-5f0bee7552d4.png)

**Comment by Thangamanir** [comment]
Fixed .

![image](https://user-images.githubusercontent.com/35291998/65398771-c09bcd80-ddeb-11e9-866e-0bbfcd7798d2.png)
