### ISSUE TITLE
DeprecationWarning could not allow path activity to be passed

### ISSUE THREAD

**Issue by horensen** [NUS-ALSET/achievements#1002]
Some path activities that make use of the requests module (python) will not allow the correct code answer to be submitted if a DeprecationWarning is thrown. 

For example: 
```
/var/runtime/botocore/vendored/requests/api.py:67: DeprecationWarning: You are using the get() function from 'botocore.vendored.requests'.  This is not a public API in botocore and will be removed in the future. Additionally, this version of requests is out of date.  We recommend you install the requests package, 'import requests' directly, and use the requests.get() function instead.
  DeprecationWarning
```

Steps to reproduce:
1. Go to any Serverless Functions activity in NUS ALSET.
2. In the code answer box, import the "requests" module.
```
try:
    import requests
except:
    from botocore.vendored import requests
```
3. Make use of the requests module such as:
```
response = requests.get(WHATEVER_URL)
```
4. Click "Run".

**Comment by Aishwarya26l** [comment]
Issue Resolved -
- botocore deprecation warning for requests has been fixed by packaging the requests package along with the lambda notebook executer(AWS lambda function).
- Serverless Functions activities has been modified to accommodate the changes.
