### ISSUE TITLE
Frozen on checking solution page for Jupyter problem

### ISSUE THREAD

**Issue by anirudhvenu** [NUS-ALSET/achievements#119]
After submitting the public colab notebook it seems to be frozen at this page

![screen shot 2018-04-16 at 1 17 16 pm](https://user-images.githubusercontent.com/20701981/38791384-e7ca86c2-4179-11e8-80c7-f77d9744455f.png)

**Comment by Brainenjii** [comment]
It could be on disabled queue processor. I'll add timeout for waiting processing result

**Comment by scboesch** [comment]
Are there steps to reliably repeat this error or is it intermittent? 
If you press the refresh button, does the waiting screen stop?

**Comment by Brainenjii** [comment]
could you retry it now? Should be fixed with last PR

**Comment by anirudhvenu** [comment]
The timeout feature seems to be working now. 
@scboesch  the error is produced if the link provided is the drive one rather than colab link. 
Ex: https://drive.google.com/file/d/1y7Z9EY0el5gg69OQdCPuCNheqR5uWOMp/view?usp=sharing
instead of 
https://colab.research.google.com/drive/1y7Z9EY0el5gg69OQdCPuCNheqR5uWOMp

**Comment by anirudhvenu** [comment]
I'll go ahead and close this. However, there seems to be a problem with timeout even when checking the correct notebook. Refer #122.
