### ISSUE TITLE
Frozen on opening the notebook problem

### ISSUE THREAD

**Issue by apurvaasf** [NUS-ALSET/achievements#120]
Frozen on clicking "Submit" solution for a Jupyter Notebook problem:
<img width="1440" alt="screen shot 2018-04-16 at 2 52 50 pm" src="https://user-images.githubusercontent.com/24805644/38794111-8bdbd110-4186-11e8-8e0e-cfded74e4fb8.png">

**Comment by apurvaasf** [comment]
Upon making the problem notebook and the solution notebook Public, it works though.

**Comment by Brainenjii** [comment]
could you retry it now? Should be fixed with last PR
