### ISSUE TITLE
Solution timeout even with correct notebook

### ISSUE THREAD

**Issue by anirudhvenu** [NUS-ALSET/achievements#122]
On submitting the correct notebook after checking solution for a while, it appears to time out. I think  it may be because the timeout mark is set before the time required to execute the notebook. 

![screen shot 2018-04-19 at 11 34 24 am](https://user-images.githubusercontent.com/20701981/38970079-0db78576-43c6-11e8-8dde-ba2c17405495.png)

For reference the notebook I am trying to execute:
![screen shot 2018-04-19 at 11 40 29 am](https://user-images.githubusercontent.com/20701981/38970167-7f6970b2-43c6-11e8-98a7-3beea46de7b3.png)

**Comment by Brainenjii** [comment]
Checking solution executes with queue handler (just as with CodeCombat profile) launched with https firebase trigger (`handleProblemSolutionQueue` at [https://console.firebase.google.com/project/achievements-dev/functions/list](here) ) If this queue handler down then processing never finishes. I pretty sure that at this case this processor just was not launched

**Comment by apurvaasf** [comment]
<img width="547" alt="screen shot 2018-04-20 at 2 17 46 pm" src="https://user-images.githubusercontent.com/24805644/39034056-859516a8-44a7-11e8-895f-731b3a32e9a1.png">
Same problem!

**Comment by apurvaasf** [comment]
<img width="547" alt="screen shot 2018-04-20 at 2 17 46 pm" src="https://user-images.githubusercontent.com/24805644/39034227-3e3c3272-44a8-11e8-86c3-25b3f2d4fff7.png">
<img width="668" alt="screen shot 2018-04-20 at 2 35 17 pm" src="https://user-images.githubusercontent.com/24805644/39034229-3e6aaa44-44a8-11e8-9ce4-5ec33ba4b575.png">
Same problem!
