### ISSUE TITLE
New assignment added taking too long to show up

### ISSUE THREAD

**Issue by apurvaasf** [NUS-ALSET/achievements#125]
Been an hour since I created the assignment. Isn't showing up in student's account yet.
From my account:
<img width="1440" alt="screen shot 2018-04-20 at 2 03 44 pm" src="https://user-images.githubusercontent.com/24805644/39035022-20584fea-44ab-11e8-8737-e780a4277f29.png">
From another account:
<img width="1408" alt="screen shot 2018-04-20 at 2 03 51 pm" src="https://user-images.githubusercontent.com/24805644/39035023-20939456-44ab-11e8-9274-92652242029e.png">

**Comment by Brainenjii** [comment]
Are both screenshot made at same machine (same timezone)?

**Comment by apurvaasf** [comment]
Yes. But different account opened in different browsers(Chrome and Safari).

**Comment by Brainenjii** [comment]
could you also try to check this course by account with missing assignment in incognito mode of both browsers?
