### ISSUE TITLE
May usability issues

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#137]
- [x] No clear feedback that solution is failing or passing. If you know what you are doing, you can watch for the Commit button to turn blue, but otherwise the feedback that the solution is failing is difficult to notice. Maybe the headers could use color and be clearer. 
Executed Solution Failing 
Failing - Final output should be empty
Executed Solution Failing - Timeout: code took longer than 30 seconds to run"
Executed Solution Passing 
- [x] Timeouts do not seem to be working. The pop-up message does not say timeout and the header does not get updated after the pop-up message goes away. Header should probably be updated to something like "Executed Solution Failing - Timeout: code took longer than 30 seconds to run"
- [x] Instructors can not hover over checkmarks to see what users have submitted to solve problems. This makes it difficult to quickly scan recent solutions and see if common mistakes are being made. It also makes it difficult to check for overfitting in competitions where participants may have hardcoded solutions just to pass the given tests. 
- [x] Change the notebook headers in the Jupyter-inline component to be “original problem”, “solution”, and “executed solution”. 
- [x] When solutions are not visible, users cannot see check marks showing when other participants have completed a problem. You have to make the solution visible for other to see checkmarks. 
- [x] When solutions are visible, users can not hover over checkmarks and see what other users have submitted. 
- [x]  Achievements gives a blank page when you try to update a submitted solution to a Jupyter Inline problem 
- [x] When creating problem on path, the table does not get updated to show that the problem has been added. However, it can still be assigned to the course.

**Comment by walkwel** [comment]
In 3rd point 
Are you talking about this hover ?
![Screenshot from 2018-09-04 00-59-26.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b62d494951cbe0011f2d53d/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f3723dd5b768ef12365456424caa53444d04bea6d37ef5f22e7a985959e8d06b0e27c66b12fdbf8417bf01bb73da4a85b1badf5edcfa7f74b9dfd0126754505a9bf54f34a7934acd5bf04be14e55a71b3360ef647b.png)u
