### ISSUE TITLE
Profile Refresh Timed Out

### ISSUE THREAD

**Issue by yanrongabc** [NUS-ALSET/achievements#142]
When I click on "Refresh Achievements" from my Profile page, it does not refresh and instead a notification pops up saying "Profile refresh timed out".
![profilerefreshtimeout](https://user-images.githubusercontent.com/35908515/40908420-48970258-6819-11e8-8651-eb7f1fcab9e5.jpg)

**Comment by Brainenjii** [comment]
Some actions require serverside processing. For `Spark` pricing plan these actions can't be processed with firebase functions and there is queue processor for that task. This queue processor should be launched with https request: https://us-central1-fir-project-3d2a4.cloudfunctions.net/handleProfileQueue
So, you have to launch this queue processor to escape problem with `Profile refresh timed out`

**Comment by yanrongabc** [comment]
ah okay thank you! ^^
