### ISSUE TITLE
current /home not rendering any content

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#164]
`const { userRecommendations } = this.props;`
and `userRecommendations` seems to be an empty Array.
```
        {userRecommendations.map(
          userRecs =>
            userRecs.items &&
            userRecs.items.length && (
              <Recommendations
                key={userRecs.title}
                recs={userRecs.items}
                title={userRecs.title}
              />
            )
        )}
```
so nothing is rendered?

**Comment by Brainenjii** [comment]
can't reproduce that. For my user w/o userRecommendations page was loaded correctly

**Comment by scboesch** [comment]
If there are userRecommendations for the user in the correct format, something should be rendered. 

![image](https://user-images.githubusercontent.com/26947311/41503675-351d531a-720c-11e8-98b0-1604677601ab.png)

**Comment by FeynmanDNA** [comment]
![image](https://user-images.githubusercontent.com/26617036/41504435-4f4a31c6-7221-11e8-86b2-1d69b3dbaed0.png)

I joined a public path called "First Public Path", which is the only public path available for me. And after joining that public path, the homepage still renders nothing. Above image is the console log. 

How can I add data to my userID in recommendation?

**Comment by Brainenjii** [comment]
oh, I thought you had completely empty page. For getting recommendations you have to fill `/userRecommendations/{userKey}/{anyRecommendationsGroupKey}/{featureKey_featureTypeKey}`.
e.g. 
```
ref("/userRecommendation/<userKey>/anyRecs").set({
  title: "Some Title",
  foo_bar: {
    feature: "foo",
    featureType: "bar",
    path: "<pathKey>",
    problem: "<problemKey>"
  }
});
```

**Comment by Brainenjii** [comment]
Maybe we should add something like `/defaultRecommendations` and show them for new users?
