### ISSUE TITLE
Console reports "uncaught e at e", for current prod and dev firebaseapp.com/#/

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#165]
The `/#/` root path of the firebaseapp online, for both the **development and production** version ([https://achievements-prod.firebaseapp.com/](url)), will show a console error as below:

```
uncaught at e at e 
 at r 
 at r 
 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at https://achievements-prod.firebaseapp.com/static/js/main.5ae754cd.js:1:387251
```

**Comment by FeynmanDNA** [comment]
for local development server, similar console complains:
![image](https://user-images.githubusercontent.com/26617036/41498369-6fd88218-719e-11e8-8a40-6ae895a2d4fc.png)

Branch: `master`
Path: `/` or `/home`
Console Error:
```
uncaught at watchLogin at watchLogin 
 at takeLatest 
 at loginHandler 
 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at http://localhost:3000/static/js/bundle.js:252408:35
```

**Comment by Brainenjii** [comment]
Confirmed, fixed at next PR
