### ISSUE TITLE
Users can submit answers to YouTube Path problems even without watching the video

### ISSUE THREAD

**Issue by yanrongabc** [NUS-ALSET/achievements#181]
There might be something weird with validateSolutions() as recent path problems created still allows for users to submit answers to youtube videos despite not watching the video at all. 
![image](https://user-images.githubusercontent.com/35908515/42612652-17b46044-85cf-11e8-9c99-e1c6101d8f8e.png)

Thank you!

**Comment by Brainenjii** [comment]
Should we allow send solution only when all video was watched, or if it was started only?

**Comment by yanrongabc** [comment]
I think as long as they played the video, it should be okay. 😄

**Comment by yanrongabc** [comment]
@Brainenjii I like the update that forces users to somehow reach the end of the video. Thanks alot! 😃
