### ISSUE TITLE
No persistent feedback for failing jupyter inline problems

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#182]
When a Jupyter inline problem fails after clicking run, there is no persistent feedback that the notebook failed or why if failed. There is a toast message that appears and disappears, but this feedback is easy to miss.

There should be text that explains that the notebook failed and why. This could be above the Calculated Solution or besides the Calculated Solution title. 

Failing - Your solution did not pass the provided tests.
              Calculated Solution

Calculated Solution (Failing - Your solution did not pass the provided tests)
Calculated Solution (Checking) 
Calculated Solution (Passing) 

 
![image](https://user-images.githubusercontent.com/26947311/42625979-ba4ae37e-85fb-11e8-8767-3db6e64770ea.png)

**Comment by Brainenjii** [comment]
Could you check this issue - is current approach valid?
