### ISSUE TITLE
Adding New Problems into Paths (Default option should not be text)

### ISSUE THREAD

**Issue by yanrongabc** [NUS-ALSET/achievements#186]
Hello :)

When creating a new problem on a Path, the default option given is Text, however this might lead users to think that they can create a Text problem by merely filling in the question name. Clicking on "Commit" after only filling in question name and **not clicking or selecting anything from the dropdown menu**, will cause this error:
![image](https://user-images.githubusercontent.com/35908515/42677623-deceeeee-86ae-11e8-8512-6a730cb64bcb.png)
I think the default option should be set to "Please Select One" or something else other than a type of question. 

Additionally, after facing the above error, if they proceed on to select an option from the dropdown menu, and fill in the necessary details for that question type before hitting "Commit", they would then face this error:
![image](https://user-images.githubusercontent.com/35908515/42677762-5bacba86-86af-11e8-8787-6d63b0ae18a7.png)

The second error requires the user to re-enter the question name, but since the input they previously keyed in still exists, it is not clear that they need to re-enter the question name to create a new question.

Thank you!

**Comment by Brainenjii** [comment]
Currently `Text` is default type for activity and requests setting `Question` field on creation. You may reopen this issue if current approach is unacceptable
