### ISSUE TITLE
Unable to reorder activities on Path

### ISSUE THREAD

**Issue by yanrongabc** [NUS-ALSET/achievements#187]
Hello

Problems on a path are ordered chronologically, with the first created problem at the top of the path, and the last created problem at the bottom. However there might be a need to rearrange the order of the problems in a path:
![image](https://user-images.githubusercontent.com/35908515/42678033-3bd76250-86b0-11e8-93f8-11f3fdc80a10.png)

Thank you! 😃

**Comment by FeynmanDNA** [comment]
@scboesch i tried on a path on prod, it seems fine. The Move Up and Move Down are wrapped inside the MORE button. 
![image](https://user-images.githubusercontent.com/26617036/48238569-6fb6fc80-e406-11e8-84ed-582fdd120ff1.png)

**Comment by FeynmanDNA** [comment]
@Brainenjii the Move Up and Move Down does not work when you try to move the order that involves Jest Activity and non-Jest activity

**Comment by scboesch** [comment]
Resolved on dev.
