### ISSUE TITLE
Rename Jupyter activities to be more consistent

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#190]
Activities which require users to submit a link to a Colaboratory notebook will be called Colaboratory Notebook Activities. 

Activities which require users to edit code for a single block in a Juptyer notebook will be called Jupyter Notebook Activities.  

![image](https://user-images.githubusercontent.com/26947311/43083447-217f5a0e-8ec9-11e8-8c25-f9477309ce78.png)

**Comment by FeynmanDNA** [comment]
we need to apply this consistency in naming for HomeV2/V3 as well. 
![image](https://user-images.githubusercontent.com/26617036/44702635-f1b1ad80-aac6-11e8-99b7-0a772f22e1a7.png)
The "jupyter" and "jupyterinline" text in the cards should be renamed accordingly.

**Comment by FeynmanDNA** [comment]
@scboesch should this renaming of "jupyterinline" and "colab" activities apply to our codebase as well?
![image](https://user-images.githubusercontent.com/26617036/44703149-173fb680-aac9-11e8-8030-8b5cfb12c703.png)

**Comment by scboesch** [comment]
We can open a refactoring issue to update the codebase, but this can be lower priority than updating the GUI to properly reflect the terms "Jupyter Notebook" and "Colaboratory Notebook". These terms seem to appear correctly in the add activity dropdown box for path editors. 

The same terminology should be used for recommendations. "Recommended Jupyter Notebook Activities" and "Recommended Colaboratory Notebook Activities".

![image](https://user-images.githubusercontent.com/26947311/44762529-00a56800-ab7a-11e8-970b-cacce714c7c1.png)

**Comment by FeynmanDNA** [comment]
temp fix from #345
