### ISSUE TITLE
Removing the ability to hit "enter" to submit solution

### ISSUE THREAD

**Issue by yanrongabc** [NUS-ALSET/achievements#193]
Inside a course, when the popup dialog appears like this:
![image](https://user-images.githubusercontent.com/35908515/43182877-b237932a-9015-11e8-9085-f2bf36568fd4.png)
Users can actually hit "enter" thinking that they submitted their solutions, but what happens is that their solution is NOT submitted, and an error message appears as shown:
![image](https://user-images.githubusercontent.com/35908515/43182892-c354e734-9015-11e8-899a-8fb8e59b9494.png)
Also note that my previous solution was "Bingsu", and I tried to update it to "icecream", but upon hitting "enter", my solution does not update and my previous solution also disappeared.

**Comment by scboesch** [comment]
@yanrongabc Closing this issue based on the last landed PR. Please re-open if you still see the issue on dev.
