### ISSUE TITLE
Course Owner Update All Button

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#212]
It should be possible for a course owner to press a button to update the path progress of all course members for an assignment based on a path. This is needed since some course members will fail to press their update buttons.

**Comment by scboesch** [comment]
The refresh button for course owners should update the path progress for all students who may have forgotten to click their update buttons recently. 

Alternatively, the update button only needs to refresh visible path progress tracking assignments and not hidden ones. 

Or, there can be a small refresh button added to path tracking assignment header column for course owners that enables them to update the progress for the tracked path for the students in the course. 

![image](https://user-images.githubusercontent.com/26947311/44072243-2f529f30-9fc0-11e8-9316-7ca9946d7553.png)

**Comment by Brainenjii** [comment]
There is little delay between `Refresh` clicking and table update. Is this delay acceptable or should be removed?

**Comment by scboesch** [comment]
There is no feedback provided while the async update is occurring, but it appears to be working properly, so we can proceed to close this issue and open an issue related to user feedback if needed.
