### ISSUE TITLE
CodeCombat Level Activity for Paths

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#215]
There should be a way to add an activity to a path which requires users to complete a specific level on CodeCombat. A CodeCombat level activity is created by providing the levelID and URL to a level on CodeCombat. This can be a level from one of the CodeCombat campaigns or a new level that an instructor has created for their course.  

Does the currently deployed version work?

**Comment by walkwel** [comment]
A CodeCombat level activity is created by providing the levelID and URL to a level on CodeCombat.

Current deployed only has only levelID dropdown no option for add URL

**Comment by scboesch** [comment]
We are changing the initial functionality to just support the levels included in the dropdown list. You can close this issue once that functionality is working for new Code Combat activities added to a path.
