### ISSUE TITLE
Jupyter Notebook activity starting code analysis

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#241]
Each time a Jupyter Notebook (inline) activity is saved, analyze the given (starter,template) code provided in the editable code block. 

- [ ] Create a trigger (and queue-based solution for dev) to determine the editable code block in the Jupyter activity, extract the python code for that editable code block. 
- [ ] Post the given code for the editable Jupyter notebook block to the lambda code analysis function. Github 
- [ ] Save the returned analysis results somewhere with the Jupyter notebook activity public data.  Refer to these code features as givenSkills.
- [ ] Provide the activity creator with a way to view the code analysis results for their given code. 

When activity creators change the given code for the editable code block, they should see the analysis change if they have removed or included more language features in their given starter code.

**Comment by walkwel** [comment]
@scboesch can you explain more language feature?
