### ISSUE TITLE
Save userSkills and problemSkills

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#246]
Save the delta (difference) between student solution code features and the given code features to the userSkills node in the database. Users should only be given credit for the code features that were in their code and not already included in the given code. (userSkills = solutionSkills - givenSkills) 
     userSkills       -> UserKey -> featureType -> feature -> problemKey -> True

For each code feature that is saved as a userSkill for a user, also add an entry to the problemSkills node. 
    problemSkills -> ProblemKey -> featureType -> feature -> userKey -> True

**Comment by walkwel** [comment]
I think this will be good if I chang the format of analysis response 
from 
```
{
  "problemSkills": {
    "problemAA": {
      "constructs": {
        "FunctionDef": {
          "userBB": true
        }
      },
      "functions": {
        "print": {
          "userBB": true
        }
      }
    }
  },
  "userSkills": {
    "userBB": {
      "constructs": {
        "FunctionDef": {
          "problemAA": true
        }
      },
      "functions": {
        "print": {
          "problemAA": true
        }
      }
    }
  }
}
```
To 
```
{
  "problemSkills": {
    "constructs": {
      "FunctionDef": true
    },
    "functions": {
      "print": true
    }
  },
  "userSkills": {
    "constructs": {
      "FunctionDef": true
    },
    "functions": {
      "print": true
    },
  }
}
```
before saving into database.
Difference calculation will be easy then.
