### ISSUE TITLE
The text for youtube activities should say answer "the" questions

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#253]
The text should say "Watch Video and answer the questions." rather than
Watch Video and answer for questions.

![image](https://user-images.githubusercontent.com/26947311/44067616-f94f50de-9fa8-11e8-9770-5b03c1ddcf96.png)

**Comment by walkwel** [comment]
Text is already "Watch Video and answer the questions"

![screenshot from 2018-08-14 15-34-49](https://user-images.githubusercontent.com/23698860/44085586-a445e90c-9fd7-11e8-9155-368a1a8c6f5f.png)
