### ISSUE TITLE
Only show the first 40 characters of text submissions

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#254]
Only show the first 40 characters of text assignment submissions. Require users to hover over the solution to see the remainder of the text in a tool tip or other popup. 

![image](https://user-images.githubusercontent.com/26947311/44071899-5b34050a-9fbe-11e8-9b60-81037f4b70e9.png)

**Comment by FeynmanDNA** [comment]
The fix provided at e3296b64a361ccbee0f8a28b3e6e9f95ee4a3a37 caused another subtle UI bug. When user hovers over the text, and if the text has overflow hidden, the horizontal scroll bar appears:
![image](https://user-images.githubusercontent.com/26617036/44129239-efc28bfe-a079-11e8-8ad0-c3ddf6de3c44.png)

**Comment by FeynmanDNA** [comment]
![image](https://user-images.githubusercontent.com/26617036/44576094-47810f80-a7c0-11e8-9caf-4a66d0c8cdbc.png)
