### ISSUE TITLE
The completed activities on a path tracking should be 1 of 2 rather than 50%

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#255]
We should show path progress as n of m rather than as a percentage. 

![image](https://user-images.githubusercontent.com/26947311/44072153-c16ad096-9fbf-11e8-8026-dca0b66c98b9.png)

**Comment by Brainenjii** [comment]
should existing solution be changed also? Or only new solutions?

**Comment by scboesch** [comment]
Only for new solutions is fine.
