### ISSUE TITLE
"Refresh" Button in Paths List showing popup of "Missing CodeCombat Profile"

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#259]
In Paths showing the a Path list of questions, the "Refresh" button on the right, when clicked displays a popup of "Missing CodeCombat Profile":
![image](https://user-images.githubusercontent.com/26617036/44073103-cf60d1dc-9fc4-11e8-9b38-f12e74f6b8e1.png)

**Comment by Brainenjii** [comment]
`Refresh` button checks CodeCombat activities status. So, it requires CodeCombat profile. But there are no CodeCombat activities on this path so this notification is useless. I'll add checking - is there any CodeCombat activity at the path before checking a profile
