### ISSUE TITLE
On Submit, it should return to the list of Activities

### ISSUE THREAD

**Issue by walkwel** [NUS-ALSET/achievements#260]
When Instructor solve an inline activity it doesn't go back to list of Activities page but for rest of the activities are.

![screen shot 2018-08-14 at 10 29 16 am](https://user-images.githubusercontent.com/23698860/44073197-51272f78-9fb0-11e8-8103-7365ba054378.png)

**Comment by FeynmanDNA** [comment]
@walkwel do you mean in a course, when an instructor solves his/her own assignment/activity, hitting "Commit" does not redirect them to the Courses page? 
Can we have more details of the issue you are encountering? Thanks.

**Comment by walkwel** [comment]
"when an instructor solves his/her own assignment/activity, hitting "Commit" does not redirect them to the ~~Courses~~ Paths/$ PathKey page".
Yes, that's what I mean.

**Comment by walkwel** [comment]
![Screenshot from 2018-09-05 06-08-01.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b62d494951cbe0011f2d53d/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f3723dd5b668ef14365157424ead53444d04bea6d37ef5f22e7a985959e8d06b0e27c66b12fdbf8417bf01bb73da4a85b1badf5edcfa7f74b9dfd0126754505a9bf54f34a8934acd5bf04ae14a5ca7153f67e6647b.png)
But know I see someone I added a

**Comment by FeynmanDNA** [comment]
i did an update on the code to implement the redirect to Path #437
