### ISSUE TITLE
[HomeV2 Recommendation Page] Update userRecommendations data and modify the homev2/v3 route to use the data. 

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#297]
Create a firebase function that can be passed a userKey. The firebase function will the update the userRecommendations for that user. 

Initial user recommendations should recommend the first 4 activities of each type (YouTube, Jupyter, Jest, Colab, Code Combat, Game ) from all public paths. This function will scan all public paths and create a list of available public activities. The function will also retrieve all activities from public paths that the users has already completed. The function will then determine the first 4 (by date created) unsolved activities of each type for the user. 

The function will save save the data to /userRecommendations/$userKey which should be readable by the logged in user with that $userKey. A lastUpdated property on the userRecommendations should be updated to the current server time each time the recommendations are updated. 

The homeV3 route should be rendered based on the current data in /userRecommendations. 

Whenever a user completes an activity on a public path, the updateUserRecommendations($userKey) function should be triggered. 

If the current user does not have any recommendations or the recommendations have not been updated in a week, the updateUserRecommendations($userKey) function should be triggered.

**Comment by FeynmanDNA** [comment]
@Brainenjii Hi I have updated some style changes and improved how the carousel button works (thanks to HomeV3) with the latest pull request #300 

The design details are commented in the code from HomeV2 folder.

**Comment by FeynmanDNA** [comment]
@Brainenjii HomeV3 is a good implementation prototype. But since we have expanding to more than just Jupyter and YouTube activities, I have written down some design ideas and thoughts for other types of Activities in HomeV2.

So please check HomeV2 first, and preferably build from HomeV2. with the #300

**Comment by Brainenjii** [comment]
@FeynmanDNA ok, I little updated HomeV2
@scboesch when (and who) should invoke this firebase function?

**Comment by scboesch** [comment]
For now, we can plan to trigger the userRecommendation updates every time a user completes/solves a new activity.

**Comment by FeynmanDNA** [comment]
@Brainenjii You are right, currently HomeV2 supports `jupyter` and `youtube` activities, and we will add Game, Jest, CodeCombat Activities eventually. For scaling purposes, feel free to implement any avatar and title props to the recommendation components.

I tried out the different avatars and titles and logo image specified in the comments in HomeV2, and they should look quite ok on a homescreen :smile: 
![image](https://user-images.githubusercontent.com/26617036/44499849-68f6d400-a6b8-11e8-90c1-a0f0f3265ba7.png)

![image](https://user-images.githubusercontent.com/26617036/44499822-4795e800-a6b8-11e8-98ab-0a76b6a5e407.png)
![image](https://user-images.githubusercontent.com/26617036/44499666-824b5080-a6b7-11e8-80ee-db1da22fa270.png)
![image](https://user-images.githubusercontent.com/26617036/44499720-c50d2880-a6b7-11e8-8f2a-a6a3f55cff06.png)
![image](https://user-images.githubusercontent.com/26617036/44499495-b3775100-a6b6-11e8-9106-d32e80d13a91.png)

For now, we will need the update and fetching of unsolved/unwatched `jupyter` and `youtube` activities for the GUI working first.

**Comment by FeynmanDNA** [comment]
a temporary solution for CodeCombat type activities is updated in #302 
![image](https://user-images.githubusercontent.com/26617036/44503201-b0d12780-a6c7-11e8-81ad-411c331c6aa9.png)
Also good to have a loading indicator for fetching wait time

**Comment by FeynmanDNA** [comment]
Now HomeV2, HomeV3, and default AltHome are all displaying some recommended activities. But when click "Learn More" on  **HomeV2**, the activity's parent URL is **DEFAULT**:
![image](https://user-images.githubusercontent.com/26617036/44568140-14328680-a7a8-11e8-8eaf-db394dfa2aa9.png)

***

While HomeV3 or the default AltHome's activities have their original parent URL intact:
![image](https://user-images.githubusercontent.com/26617036/44568192-4e9c2380-a7a8-11e8-9d8d-551d8f64e6f6.png)

**Comment by FeynmanDNA** [comment]
Now HomeV2 is still fetching path activities from those that not marked as "isPublic".

For example, I have made only one YouTube path as "isPublic":
![image](https://user-images.githubusercontent.com/26617036/44568635-3d541680-a7aa-11e8-8137-d74344479c73.png)

And that path is made up of YouTube activities alone.

***


However, HomeV2 is currently displaying two other rows of activities with CodeCombat and Jupyter:

![image](https://user-images.githubusercontent.com/26617036/44568629-362d0880-a7aa-11e8-935d-a19e7670a823.png)

**Comment by Brainenjii** [comment]
Currently userRecommendation fetcher never remove anything from /userRecommendations` node. I'll fix it this weekend

**Comment by FeynmanDNA** [comment]
@Brainenjii Please help to look into the other problems in this discussion as well:
1. the `DEFAULT > Activities` in the breadcrumb when clicking the HomeV2's "Learn More" button.
2. avatar/icon/logo-image/color as props for recommendationList associated with different types of activities.
