### ISSUE TITLE
Logout button not functioning.

### ISSUE THREAD

**Issue by apurvaasf** [NUS-ALSET/achievements#3]
The logout button has no popup upon clicking on it.

**Comment by Brainenjii** [comment]
What popup should appear on click? Confirmation dialog?

**Comment by apurvaasf** [comment]
That popup that needed to appear: <img width="1102" alt="screen shot 2018-01-31 at 9 22 48 am" src="https://user-images.githubusercontent.com/24805644/35600371-851179b0-0668-11e8-95bd-51fc20cbc660.png">
Unlike the code before the latest one, it appears in the latest code deployed. Thanks.
