### ISSUE TITLE
Interesting text artifact

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#303]
![image](https://user-images.githubusercontent.com/26947311/44504855-d0b91900-a6d0-11e8-928f-d208927b3c09.png)

**Comment by FeynmanDNA** [comment]
i am able to reproduce this error with the following text:
![image](https://user-images.githubusercontent.com/26617036/44524094-cc135580-a70e-11e8-9151-97d66f9f565f.png)
![image](https://user-images.githubusercontent.com/26617036/44524130-ee0cd800-a70e-11e8-8bb1-89580b5f5920.png)

**Comment by FeynmanDNA** [comment]
i implemented a regex check for printable-keyboard inputs for AddTextSolutionDialog component.
So we will guide the users to input more sensible texts for team names and simple text questions.
#308
