### ISSUE TITLE
Refactor: AddAssignmentDialog.js `onKeyPress` for TextField duplicate function?

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#313]
![image](https://user-images.githubusercontent.com/26617036/44617689-e0378e00-a899-11e8-8510-fc6ae9a3d983.png)

I tried to remove onKeyPress and the `manualChangeField` related code, and the app seems to be working fine.

Do we need both `onChange` and `onKeyPress` for "name" and "details" fields?

**Comment by Brainenjii** [comment]
`onKeyPress` handler supposed to detect manually change of field value. In the case of manual change, it should prevent autofill this field by selecting other fields, e.g. CodeCombat `level` field. But, I think we don't need that feature, so we could remove it.

**Comment by FeynmanDNA** [comment]
removed in #324
