### ISSUE TITLE
Implement process to analyze default solution notebooks and save all used skills. 

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#316]
Jupyter and Colab notebook problems require an example solution. 
After activities are saved, start a process to download the default solution notebook, collect the python code from ALL code blocks, post all the combined source code to the code analysis service, save the results to the defaultSolutionSkills node in the private database location where the solution url is securely saved.

**Comment by walkwel** [comment]
Solution URL is currently saved in a public location along with the activity data. So at which collection should I save the URL and skills?
