### ISSUE TITLE
Problem solution code analysis includes names of functions defined in the notebook itself

### ISSUE THREAD

**Issue by veloman-yunkan** [NUS-ALSET/achievements#328]
The analysis of the solution to the `numpy.where` Jupyter activity at [this path](https://achievements-dev.firebaseapp.com/#/paths/-LJmdXWBgsNkzRC6piLm) (see screenshot below) includes two functions `check_eligibility` and `check_eligibility_reference_impl` that are defined in the notebook itself. Such functions should not be included in the set of the skills that the students should demonstrate.

![screenshot](https://user-images.githubusercontent.com/11933502/44710474-42240d80-aabd-11e8-9400-5beab5ccd1c3.png)

**Comment by scboesch** [comment]
We will update this code analysis in the code analysis service rather than in the Achievements codebase.
