### ISSUE TITLE
Inconsistent way of referring to the default code block in Jupyter activities

### ISSUE THREAD

**Issue by veloman-yunkan** [NUS-ALSET/achievements#330]
In the
[numpy.where](https://achievements-dev.firebaseapp.com/#/paths/-LJmdXWBgsNkzRC6piLm/activities/-LKrqCs7kiXOVMN3lpyG) Jupyter activity I have to refer to the default code block as #1. Although it is the 2nd cell of the notebook it is indeed the 1st code cell. This makes sense.
![Editing the "numpy.where" activity](https://user-images.githubusercontent.com/11933502/44711663-f1fa7a80-aabf-11e8-9569-2f510d6c2d7d.png)

Whereas in the [Multitarget assignment](https://achievements-dev.firebaseapp.com/#/paths/-LJmdXWBgsNkzRC6piLm/activities/-LKroz5VgpciMejMhMOD) Jupyter activity the default code block is the 2nd code cell and the 4th cell overall, however I must refer to it as #3.
![Editing the "Multitarget assignment" activity](https://user-images.githubusercontent.com/11933502/44711768-2f5f0800-aac0-11e8-8293-83871fafc72c.png)

Note that if this issue report is acknowledged to be a problem, fixing it may break preexisting activities similar to the second case above. The default code fields of all such activities must be updated together with the code that handles it.

**Comment by FeynmanDNA** [comment]
@veloman-yunkan we have made some update to the Jupyter Notebook Activity UI for the Add Activity Dialog:
![image](https://user-images.githubusercontent.com/26617036/45526284-1f0d9380-b809-11e8-825f-dc91933cc3fa.png)
which is live in the achievements-dev version.

It is still a work in progress, please feel free to tell us what can be improved and what should we stop doing. Would love to hear your feedback on this.

And for the questions you have in this issue:
so " default code block" (now changed to "Index of Code Block Student Can Edit Solution (Index starts from 0)"), it is the index of the block of the jupyter notebook. And the blocks can be text or code block. I think it is helpful to keep in mind that index of Colab notebooks start from 0. 

Let us know your feedback on the new UI :)

**Comment by veloman-yunkan** [comment]
> I think it is helpful to keep in mind that index of Colab notebooks start from 0.

I have a long software engineering experience and 0-based indexing is the default for me while programming. However, I completely failed to realize that it might be assumed in a user interface. Given that changing that will require updating existing data, I admit that the current notice '(Index starts from 0)' is an acceptable solution to the problem.
