### ISSUE TITLE
[HomeV2 Recommendation Page] Carousel Ajax Loading Indicator Inside Each Card

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#335]
Users should be able to see skeletons of the Carousel, and an ajax loading indicator for lazy loading while waiting for the content of the Recommendation Carousel to appear:

![image](https://user-images.githubusercontent.com/26617036/44773999-8fc77580-aba4-11e8-81be-3035bcbc9e63.png)

If a Carousel row is to be recommended to a user, first render the skeleton of the Avatar+Color+Name+logoImg etc with a linearprogress from material-ui.

**Comment by walkwel** [comment]
Here all recommendations were loaded in single firebase query.
So I think there will be a single loader for all.

**Comment by FeynmanDNA** [comment]
@walkwel is it possible for us to not load everything in one single query? Can we fetch the recommendation type, for example, so we know how many carousels and which avatar+color+logoImage to use, then show the loading indicator while waiting for the rest of the data to arrive?

**Comment by FeynmanDNA** [comment]
follow up on the comment above: even before the recommendation type arrives, we can maybe show the users two carousels with gray areas waiting for the recommendation type data to be read

kind of like this effect:
![image](https://user-images.githubusercontent.com/26617036/44947254-f797ed80-ae3c-11e8-82a4-cf36214f7906.png)
