### ISSUE TITLE
[HomeV2 Recommendation Page] Detect if the user is logged in for the first few times

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#338]
If a user is joining the Achievements app for the first time or still among the first few times after logging in, the HomeV2 Recommendation Carousel's subheader should not be "Recommended for you" but should be:
![image](https://user-images.githubusercontent.com/26617036/44780353-55fe6b00-abb4-11e8-85f9-b8d672413c9d.png)

only for users that have indeed participated in our activities, we can have customized "Recommended for you"

**Comment by Brainenjii** [comment]
Maybe we could prepare default recommendations list and show it to unlogged users and users w/o any solved activity from this default list. After solving any of these activities - recalculate user's recommendations

**Comment by FeynmanDNA** [comment]
@Brainenjii i think currently this app is not going to consider the need of unlogged users (with many pages and contents requiring login in the first place).

The default recommendations lists can definitely be shown to first-few-time login users.

**Comment by FeynmanDNA** [comment]
@Brainenjii we will have a UX team figuring out how to implement the app UI for unlogged users. But in this case, logged-in for the first time or first few times should be seeing the same content (our suggested/default activities) as unlogged users

**Comment by FeynmanDNA** [comment]
Please refer to two related updates on the UX workflow on this issue

1. #383 Default Homepage/Recommendations for Non-logged users
2. #384 UX for Non-logged Users Home/Paths/Register
