### ISSUE TITLE
Solution Notebook URL is not saved (Jupyter/Colab)

### ISSUE THREAD

**Issue by veloman-yunkan** [NUS-ALSET/achievements#339]
When adding a new Jupyter Notebook activity the entered Solution Notebook URL is not saved on commit (that field appears empty when reopening the activity editing dialog).

**Comment by FeynmanDNA** [comment]
@veloman-yunkan do you mean like this:
![image](https://user-images.githubusercontent.com/26617036/44797380-a93ae280-abe1-11e8-877a-14ed658016f3.png)

and i think the solution URL might also be missing for Colab activities too:
![image](https://user-images.githubusercontent.com/26617036/44797570-177fa500-abe2-11e8-8fa1-7d01f159659e.png)

**Comment by walkwel** [comment]
Solution URL is not saved along with other information in activities collections, It's saved at path activityExampleSolutions/$activityKey to make this private from users.
I should fetch this URL from activityExampleSolutions collection to show here.
