### ISSUE TITLE
YouTube Activity Commit Button Empty Solutions Error

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#343]
After fix in [commit](https://github.com/NUS-ALSET/achievements/commit/508219cf12d1352f417ac863c320eff9058aeebd), new issues of YouTube activity as followed:
When the solution to the question is empty, the popup of error is not "missing answer for ..." but 
![image](https://user-images.githubusercontent.com/26617036/44829999-16865c00-ac52-11e8-99f5-f46f60efde1e.png)
![image](https://user-images.githubusercontent.com/26617036/44830102-9f04fc80-ac52-11e8-98de-e7c8e1589d1a.png)

**Comment by Brainenjii** [comment]
should be fixed in #358 also
