### ISSUE TITLE
Log all clicked on user recommendation events

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#359]
Whenever a user clicks on a user recommendation on the home screen, log the current state of  userRecommendations/$userKey for the user, the userKey, the current time, and the recommended item in the home screen GUI that the user clicked on. Log this information as a new node in /loggedRecommendationEvents.  This node should only be writeable by users and the security rules should only permit the current user to log new events to this node that contain the current user's userKey.

**Comment by FeynmanDNA** [comment]
@scboesch I checked the database of firebase dev, and could not find any node that is logging the recommendation or the Home page actions.

**Comment by FeynmanDNA** [comment]
> Log this information as a new node in /loggedRecommendationEvents.

@scboesch @Brainenjii The current implementation is not creating a new node, but still logging the data to the `logged_events` node:
![image](https://user-images.githubusercontent.com/26617036/45946700-46900780-c024-11e8-8623-cd0a7a33257f.png)

**Comment by FeynmanDNA** [comment]
@scboesch sorry, this is where we log the events to firebase:
![image](https://user-images.githubusercontent.com/26617036/45947341-6d4f3d80-c026-11e8-8b82-40be22c524b5.png)

**Comment by FeynmanDNA** [comment]
The current logged data in the database is bit incomplete, if not misleading at times. For example, one of the recent logged data from my account  on dev is:
```javascript
  "-LMv4sfMZXjnaPdEA7Ef" : {
    "createdAt" : 1537515948975,
    "otherActionData" : {
      "activityId" : "-LJHr8nSwwLHMf-13bTh",
      "pathId" : "-LJHqMIfJUJhR2eAGKKE",
      "recommendationType" : "game",
      "recommendations" : "{\"codeCombat\":[\"-LJHr1q2Oar3qSVWsped\",\"-LJHr8nSwwLHMf-13bTh\",\"-LJHrKDIQBechnHlTwTY\",\"title\"],\"jupyterInline\":[\"-LM1NG5WtpMo06_yFNjP\",\"-LM7wOmh-_DT4-b_QwWb\",\"-LMGlgmcViNk1z8kUD4v\",\"-LMfAM_9vPA2dUy09IkE\",\"-LMfFqUXsXSL-ajrdKP7\",\"-LMfKzcXzNTB8ul5Lg80\",\"-LMfP-DlhgkThaaZHuQO\",\"-LMfVIBPOabH9FbOoPCf\",\"-LMfha24acSQTZlgadQX\",\"-LMfjtP3zOhCZSPB3r2X\",\"-LMkKzS2y9I-A_e4ScmP\",\"-LMpOuLrTD5GiY0TzEe-\",\"title\"],\"solvedPySkills\":[\"title\"],\"unSolvedPySkills\":[\"constructs_FunctionDef\",\"expressions_Eq\",\"expressions_Mult\",\"functions_multiply\",\"functions_print\",\"functions_sum\",\"statements_Assert\",\"statements_Return\",\"title\"],\"youtube\":[\"-LKe_zLCjXM9zRpvdzaX\",\"-LKeaA6QHTCAxWA-CShP\",\"-LKearmKLmPKLIh4VAl-\",\"-LLhxLbMvaXf1e-REmQN\",\"title\"]}"
    },
    "type" : "HOME_OPEN_RECOMMENDATION",
    "uid" : "I9nQZbQ5xMdklnudDqGfh1ucOZz2"
  },
```
The "recommendationType" is recorded as "game", but the recommendations contains codecombat + jupyterInline + youtube + solvedPySkills.
And we are not recording the clicked on Activity of the card in the carousel.

**Comment by FeynmanDNA** [comment]
@Brainenjii sorry, i realize this code is recording the clicked on event on the homescreen:
![image](https://user-images.githubusercontent.com/26617036/45948003-e51e6780-c028-11e8-9a84-4ea11d704623.png)
