### ISSUE TITLE
Confusing variable names (PySkills) in functions folder

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#362]
![image](https://user-images.githubusercontent.com/26617036/44985544-4b2c4780-afb3-11e8-9c31-612286a9f010.png)

It is difficult to understand if solvedPySkills and unSolvedPySkills are the reason why we are recommending those Jupyter activities? Or do solvedPySkills and unSolvedPySkills stand for the jupyter activities themselves? 

The variable/key names should be consistent with the rest of the naming style:
![image](https://user-images.githubusercontent.com/26617036/44985705-d60d4200-afb3-11e8-93a2-d446d41bcf88.png)

Please rename the solvedPySkills and unSolvedPySkills to be consistent with the rest of the object, where the name on the left **stands for** the description text on the right.

**Comment by walkwel** [comment]
solvedPySkills, unSolvedPySkills - these recommendations are only based on jupyter & jupyterInline activities.
unSolvedPySkills - these are those public unsolved(by user) activities which contain python skills/features which user has not solved yet.
solvedPySkills - these are those public unsolved(by user) activities which contain python skills which user has already solved.

We can change the name of the variable like that - 
unknownPyhonFeaturesActivities, knownPythonFeaturesActivities
or
unknownPyhonSkillsActivities, knownPythonSkillsActivities

Please suggest a better name for the variables, if you have in your mind.

**Comment by FeynmanDNA** [comment]
@walkwel I have made some changes to the naming of the PySkills variables in #379. 
My new suggestions are:

- NotebookWithNewSkills
- NotebookWithUsedSkills
