### ISSUE TITLE
Home Recommending Activities with New Skills and Not-attempted categories  

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#381]
This is more of an architectural question about our home screen.

Currently we are recommending Jupyter/Colab activities that are not-attempted, and that contains new python skills. 

I am wondering if the recommendation is based on **not-attempted** activities, shouldn't the **with-new-skills** overlap with the not-attempted activities?

![image](https://user-images.githubusercontent.com/26617036/45071374-7d02f280-b108-11e8-9784-bb9b90e0626c.png)

How is the **with-new-skills** recommendations being triggered now? Logically, the **not-attempted** activities are the ones **with-new-skills** right?

**Comment by walkwel** [comment]
>How are the with-new-skills recommendations being triggered now?

firebase function **updateUserRecommendations**  trigger every time /users/${uid}/lastAuthTime changed.

>Logically, the not-attempted activities are the ones with-new-skills right?

Both activities **not-completed** && **new skills**  are unattempted  by the user.
But **not-completed** activities may or may not contains new skills.

So recommendation **Jupyter Notebook Activities with new skills**  show only those unattempted activities which require new skills.

**Comment by FeynmanDNA** [comment]
"But not-completed activities may or may not contains new skills." I didn't realize this before. Thanks for the clarification.

**Comment by FeynmanDNA** [comment]
@walkwel but the update of the recommendations should also be triggered whenever the user has solved/watched new public activities too right? Or in the case of recommending PySkills, the update of recommendations will be triggered if new/used python skills are detected?
