### ISSUE TITLE
Trigger Update on Recommendations for Home Page When Home route is clicked

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#386]
From my understanding (#381), the update/refresh of the recommendations data for Home Page is triggered when 

> firebase function updateUserRecommendations trigger every time /users/${uid}/lastAuthTime changed.

Please add another trigger for the update when the users click into the Home route, maybe something like `componentDidMount` when Home container is mounted. So when the Home page is revisited the recommendations are updated as well (in case we add new public activities).

**Comment by Brainenjii** [comment]
it also triggered on public activity solution, so you should get updated recommendations list after solving something from recommendations

**Comment by FeynmanDNA** [comment]
so the update is also triggered in these two cases as well?
https://github.com/NUS-ALSET/achievements/issues/381#issuecomment-418996281

![image](https://user-images.githubusercontent.com/26617036/45142543-65506a80-b1eb-11e8-91fa-a8637ac6d08e.png)
