### ISSUE TITLE
Enable users to add additional information to their profile and select what should be make public. 

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#394]
Enable users to decide what information on their profile is public and what is private. Provide toggle switches to let users hide their displayName and CodeCombat details. 

Then add the options for users to add additional information from dropdown boxes. 
- Country (Start with the options Singapore and Other)
- School Type (Continuing Education, University, Polytechnic, Junior College, Secondary, Primary)
- School  (Start with the options National University of Singapore, NUSHS, Singapore Polytechnic and Other)

If National University of Singapore is selected as the school, show an additional option to select Faculty
- Faculty (Start with Business, Computing, and Engineering as the initial options.)

**Comment by FeynmanDNA** [comment]
Please refer to the red-box outlined area in the mockup provided for the design:
![image](https://user-images.githubusercontent.com/26617036/45255907-207e2c80-b3c1-11e8-916c-dd166a8015c2.png)
