### ISSUE TITLE
Profile Route /profile/non-logged TypeError

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#395]
This error is shown in `/profile/non-logged` route:
![image](https://user-images.githubusercontent.com/26617036/45255468-8ff01e00-b3b9-11e8-88c1-b527fd308274.png)

```javascript
TypeError: Cannot read property 'displayName' of null
Function.mapStateToProps [as mapToProps]
```

**Comment by Brainenjii** [comment]
It seems like closed already
