### ISSUE TITLE
Jupyter Notebook Activity Top Commit Button Click to TypeError

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#405]
The Commit Button on top of the Run button, click will produce:
![image](https://user-images.githubusercontent.com/26617036/45342860-c43e2700-b5d1-11e8-925b-fa42dd1410e9.png)
![image](https://user-images.githubusercontent.com/26617036/45342900-de780500-b5d1-11e8-8d37-706d5f54f5d1.png)

**Comment by Brainenjii** [comment]
It seems like fixed already
