### ISSUE TITLE
Change the default text and details link for path progress assignments

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#431]
The default text for path progress assignments should be "Complete activities on the path {path name}."

The path name can be provided as the hyperlink to the path rather than providing a hyperlinked "details". 

![image](https://user-images.githubusercontent.com/26947311/45606839-13c19e80-ba7b-11e8-921d-abada8694c1a.png)

**Comment by FeynmanDNA** [comment]
Path progress's link to the path is now in the "Go to Path"
![image](https://user-images.githubusercontent.com/26617036/46537382-c13e0a00-c8e3-11e8-99b5-0ceeed6ac467.png)

The default text is now fixed with #505
