### ISSUE TITLE
Jupyter Inline/Notebook "is Loading..." but is actually frozen

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#436]
It seems that sometimes a very simple Colab ipynb (with only simple statements like a=2) cannot be loaded onto the Jupyter Notebook Activity page.

And it seems once the Colab ipynb is loaded to the Activity page, any update in the change on the Colab's side will be saved and updated in the Activity side as well (which is nice). However, the same ipynb on Colab could be un-loadable to the app one minute before!

So what is causing some ipynb to be loading significantly slower or unable to load to Jupyter Activity page?

And "is loading..." is not true, I have found that if a Colab cannot be loaded within the first 10 seconds, then chances are it is actually frozen and will never be loaded.

**Comment by Brainenjii** [comment]
could you also give link to broken activity, pls?

**Comment by FeynmanDNA** [comment]
@Brainenjii 
Here are the two examples I encountered today:
Link1:
Colab: https://colab.research.google.com/drive/1ANtBKB5nDGdHc6HWeXKowox9hEz_h1Hx
(with plot from matplotlib, the ipynb wont load)

Link2:
Colab: https://colab.research.google.com/drive/1FWRnfNaka64reOJOOy4J797swZRbOu4b
(with Image from IPython, also wont load)

I have made a path with these Colab links as Path Activities:
Path: https://achievements-dev.firebaseapp.com/#/paths/-LKySkg663NzWlsliMcf

Hope it helps!

**Comment by Brainenjii** [comment]
Awesome, thx! Seems like issue with logging events:
```
Error: Reference.push failed: first argument  contains an invalid key (text/plain) in property 'logged_events.otherActionData.payload.problemJSON.cells.1.outputs.0.data'.  Keys must be non-empty strings and can't contain ".", "#", "$", "/", "[", or "]"
```

**Comment by FeynmanDNA** [comment]
Wow! Nice! Where are these logging information found?

**And I have just managed to reproduce the most peculiar case today:**
**Colab Link: https://colab.research.google.com/drive/15RksT0xa6ppt6XRU7akGQEkhudwjivLV**
(simple a = 2 kind statements..., but still cannot load!)


Path-Activity: https://achievements-dev.firebaseapp.com/#/paths/-LKySkg663NzWlsliMcf/activities/-LMfqLNw1fhRQ6BmG4Xo

**Comment by scboesch** [comment]
I confirm that any notebook with ANY output for ANY code block will prevent the notebook from loading. Here is a very simple example. @Brainenjii  can you create a Jupyter activity with this notebook and see it load? 

https://colab.research.google.com/drive/1FmxVKooEmOQVokfASfcFG2i48WwbTiRB

**Comment by Brainenjii** [comment]
it seems the problem with python commentaries (strings started with `#` char)

**Comment by FeynmanDNA** [comment]
@Brainenjii I have made some activities that involve print() and text, like this:
https://achievements-dev.firebaseapp.com/#/paths/-LMfAB4SNR25AyoFLmN5/activities/-LMfAM_9vPA2dUy09IkE

![image](https://user-images.githubusercontent.com/26617036/45888878-b79ba900-bdf1-11e8-964e-7a2e0da18fcd.png)

and this activity for example works without the frozen loading issue. 

So is the problem with print() text?

**Comment by FeynmanDNA** [comment]
> ok, it seems the problem with cells that prints some text. Jupyter stores text output as `{.."text/plain": "Text"..}` and firebase forbid `\` char using as node
> E.g. if we remove that output from your [notebook](https://colab.research.google.com/drive/1dZLPiUJ6MasND9_f4ZFZMkyDD5WMFtVY#scrollTo=7T9eNcflO_Ln) - it'll [open](https://achievements-dev.firebaseapp.com/#/paths/-LIK_9ODuziWUhBlOvUQ/activities/-LMqbcQaNCfjrohtaBLu) but if you'll try to solve it - firebase function will meet the same issue. 

I think related to my above comment on print() and text, for your "open" link example, I am also able to solve it:
![image](https://user-images.githubusercontent.com/26617036/45889146-43add080-bdf2-11e8-9370-5b56ee94149c.png)

Any advice on this?

**Comment by Brainenjii** [comment]
I added little [change](https://github.com/NUS-ALSET/achievements/blob/master/src/services/actions.js#L26) to avoid `frozen` state. But it still fails if you'll give plain text output for a node (try to use `"true"` as the solution in your activity and you'll get an error in development console). However, it allows keeping the solution in spite of this error. For now, I don't understand how it could be so, I'm checking it

**Comment by Brainenjii** [comment]
ok, found. Firebase function that handles jupyter solutions keeps the solution from lambda function as stringified JSON. It allows receiving solution at browser page. The stored solution has no output, so it allows to keep it as _real_ JSON in firebase
