### ISSUE TITLE
Clicking solve on a Code Combat path activity should open the level in another tab

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#440]
Users should be able to open up the next code combat level on a path that they haven't solved by clicking the solved button. If the level has not been solved (after refreshing profile), the message can say "Opening up this level in another tab."

If the level has already been solved, then the checkmark should be shown.

**Comment by FeynmanDNA** [comment]
related to the feature request #465 
if the CodeCombat's profile is empty in Profile's page or the "Enter your Code Combat username" question, click Solve in the CodeCombat Levels should display a popup message of:
![image](https://user-images.githubusercontent.com/26617036/46007251-27f54380-c0ec-11e8-8ed8-513b718f841a.png)

Please implement a check for CodeCombat Profile or the status check for "Enter your Code Combat username" question. If fulfills the CodeCombat profile check, first refresh the achievements of that profile. Then either display the checkmark or redirect to the CodeCombat level.
