### ISSUE TITLE
Free CodeCombat Level Path Page Actions Column Mismatch

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#441]
![image](https://user-images.githubusercontent.com/26617036/45732474-105f1c00-bc0f-11e8-868e-724193a8aa2e.png)

![image](https://user-images.githubusercontent.com/26617036/45732490-2836a000-bc0f-11e8-9b0e-6f3f143f664f.png)

The "Solve" Button is not aligned with the Actions Column.

**Comment by Brainenjii** [comment]
There was added style to right align items in this column - https://github.com/NUS-ALSET/achievements/commit/6287d03c6fa01e13d8588178e5967d5de437471f#diff-34ca63ebfb0d51cdfcc5b29bc5742f3aR136
I don't sure what was a point for this, but maybe it's necessary for some reason

**Comment by FeynmanDNA** [comment]
I did a temp #451 fix to align "left". We can work out a prettier solution after Nov's competition.
