### ISSUE TITLE
Update Path Progress Click to "Unhandled Rejection(TypeError)"

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#442]
![image](https://user-images.githubusercontent.com/26617036/45732715-291c0180-bc10-11e8-929b-6222fab233bc.png)
Unhandled Rejection (TypeError): Cannot read property 'map' of undefined

**Comment by FeynmanDNA** [comment]
![image](https://user-images.githubusercontent.com/26617036/45732748-523c9200-bc10-11e8-8d8b-2a686622244c.png)
When click "Update Path Progress", the error appears.

**Comment by Brainenjii** [comment]
Can't reproduce - https://achievements-dev.firebaseapp.com/#/courses/-L5IiIRBig4eetfc6BbT
Could you provide link to your course?

**Comment by FeynmanDNA** [comment]
The course that gave the error was the ace2018-test-2 in the public cohort:
![image](https://user-images.githubusercontent.com/26617036/45925182-22a8c500-bf43-11e8-8c49-f36e9a3a5808.png)

But now it seems to be fixed... I guess it must be related to the "editableBlockCode" in jupyter-inline activities?
