### ISSUE TITLE
COHORT_COURSES_RECALCULATE_FAIL

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#453]
I have created a public Cohort for testing on dev:
https://achievements-dev.firebaseapp.com/#/cohorts/-LN8gtzMjUzkLyuo1yOp
![image](https://user-images.githubusercontent.com/26617036/45944315-560b5280-c01c-11e8-9e16-77d31fcdad11.png)

There are two issues here:

1. When a new user join the Course by clicking the course link, and the cohort instructor click "Recalculate", the console report the following error:
![image](https://user-images.githubusercontent.com/26617036/45944438-bac6ad00-c01c-11e8-8505-99e3e8aca226.png)

2. For the user who is seeing the public cohort page,
![image](https://user-images.githubusercontent.com/26617036/45945228-62dd7580-c01f-11e8-8807-0e6fe089800d.png)
The user's console is getting another recalculate_fail message:
![image](https://user-images.githubusercontent.com/26617036/45945271-93bdaa80-c01f-11e8-80d4-dbb083bf3b8f.png)

**Comment by FeynmanDNA** [comment]
@Brainenjii you can see the screenshots in this issue missing the Path Data name in the Table Head as well.

**Comment by walkwel** [comment]
@FeynmanDNA 
I checked this issue, but it's worked on my end.
![cohort-table](https://user-images.githubusercontent.com/23698860/46045618-ceb50080-c13b-11e8-9b0d-d7627032406e.png)
