### ISSUE TITLE
Cohort User Count 0/Empty even after "Recalculate"

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#454]
If you join my test public cohort "Mock Ace 2018 Dev" and enroll in any of the courses, 
![image](https://user-images.githubusercontent.com/26617036/45949903-1d757400-c030-11e8-9b91-2944199a9c47.png)

The password to all the schools/courses are "test".

There are several issues with this page:

1. The total student joined is often 0 even when the creator of the cohort hit "Recalculate". (it sometimes updates correctly, but there is a notable lag)

2. Often the Paths Data Table Header is not being rendered:
![image](https://user-images.githubusercontent.com/26617036/45950807-d8534100-c033-11e8-96f8-ca0124b4c457.png)

Please help debug the lagging of the fetching of data/recalculate.

**Comment by FeynmanDNA** [comment]
Can this be related to this?
![image](https://user-images.githubusercontent.com/26617036/45952699-6a5e4800-c03a-11e8-96ad-48c9d1f6259d.png)

**Comment by FeynmanDNA** [comment]
feel free to add me to your cohorts and test the Recalculate update issue. Thanks

**Comment by Brainenjii** [comment]
Hello. You have to be owner (or collaborator) on every course included to cohort to recalculate its explorers

**Comment by FeynmanDNA** [comment]
@Brainenjii hi! I am the owner on all the courses I am testing on this public testing cohort.

I am wondering can this be due to #453 issue?

**Comment by Brainenjii** [comment]
hm, that's strange. If you're owner then you should have required rights. I'll check it now

**Comment by Brainenjii** [comment]
Could you check it after #460 deploy?
