### ISSUE TITLE
Error retrieving data for path

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#455]
![image](https://user-images.githubusercontent.com/26617036/45952939-24ee4a80-c03b-11e8-9b47-9833404268b1.png)

![image](https://user-images.githubusercontent.com/26617036/45953026-654dc880-c03b-11e8-9ea5-9d358b848f1c.png)

What is the solution node in our database? And why is this particular solution value in the console as an error report?

**Comment by Brainenjii** [comment]
recalculation takes PathProgress assignments to calculate path credits at cohorts. So, it need access to these solutions. Only course owner and course participants have such rights

**Comment by FeynmanDNA** [comment]
hi is recalculation called without clicking the Recalculate button?
![image](https://user-images.githubusercontent.com/26617036/45958155-435b4280-c049-11e8-96a2-050a0a1cdf92.png)

for example, I open the Cohort page, and in the console, there are already some Recalculation_Request and Recalculation_Fail messages.

**Comment by FeynmanDNA** [comment]
And this example:
![image](https://user-images.githubusercontent.com/26617036/45958588-6df9cb00-c04a-11e8-9d6c-9dc45528230a.png)
https://achievements-dev.firebaseapp.com/#/cohorts/-LNA26JtkcTBWbWKgYrH

I am not the instructor of the cohort, and there is no "Recalculate" button for me to click, but the console is displaying quite a number of "Recalculate_Fail" messages.

**Comment by Brainenjii** [comment]
yup, it also should be invoked on cohort page open. `Recalculate` button used only for refresh requesting w/o page update

**Comment by FeynmanDNA** [comment]
is Recalculate_fail related to the blank Table Header for Paths Data?
![image](https://user-images.githubusercontent.com/26617036/45963399-ace14e00-c055-11e8-8a3b-785a893de8f8.png)

if not, we can postpone fixing Recalculate unless the Cohort being viewed is created by the user to after Nov.

**Comment by FeynmanDNA** [comment]
> Did you select paths for this cohort at Cohort creation dialog?

yes. i think the issue is with not calling the fetch paths/pathID actions. i have opened a new issue in #461

**Comment by Brainenjii** [comment]
![image](https://user-images.githubusercontent.com/774210/45994237-5f87cf80-c09b-11e8-85a2-98f0f444ce34.png)
I see all paths names. Could you try after last PR?

**Comment by FeynmanDNA** [comment]
@Brainenjii thank you! well, i get this missing paths name bug more often when i open the cohort page for the first time, after refresh the page it is often fine.
very strange indeed!

**Comment by Brainenjii** [comment]
it has non common way to set `firebaseConnect` [settings](https://github.com/NUS-ALSET/achievements/blob/master/src/containers/Cohort/Cohort.js#L196). I pretty sure it's reason of this bug. I'll update it to more reliable way
