### ISSUE TITLE
Profile CodeCombat Refresh Achievements Timeout

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#464]
Refresh Achievements with a valid account will not fetch the achievements, instead will have a timeout error popup:
![image](https://user-images.githubusercontent.com/26617036/46006178-78b76d00-c0e9-11e8-96c5-5284c5192449.png)

**Comment by walkwel** [comment]
@FeynmanDNA 
Did you start the firebase triggers locally?
If not then go the functions folder & run `npm start `command.

**Comment by FeynmanDNA** [comment]
@walkwel wow. it works!

**Comment by FeynmanDNA** [comment]
Now there is no longer a "timed out" error popup, but the achievements are not updated...
![image](https://user-images.githubusercontent.com/26617036/46245515-42e3f280-c421-11e8-9db2-f048255a8760.png)

**Comment by FeynmanDNA** [comment]
the problem was due to old code (in functions/src/updateProfile.js) not being updated.
