### ISSUE TITLE
Cohort Explorers Calculation Wrongly

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#499]
![image](https://user-images.githubusercontent.com/26617036/46518442-c16be480-c8a6-11e8-9d02-8946d002a9ff.png)

This course (Raffles Institution) is on the dev-site's cohort: https://achievements-dev.firebaseapp.com/#/cohorts/-LN8gtzMjUzkLyuo1yOp

![image](https://user-images.githubusercontent.com/26617036/46518462-dfd1e000-c8a6-11e8-8db2-35f409423b34.png)

The Explorer (completed at least threshold number of activities) should be counted as 3, but the current cohort counts only 2 explorers for Raffles Institution.

**Comment by Brainenjii** [comment]
I see now 3 explorers for this course. Mb it just delay between calculation and fetching results into page?

**Comment by FeynmanDNA** [comment]
Update on the issue:
Only initiator of recalculation get results immediately. Others need reopen cohort route. Recalculation is done with dispatched `COHORT_COURSES_RECALCULATE_REQUEST` action.
Recalculate action shouldn't update anyhow until page will be refreshed by any course participant or `recalculate` page will be clicked.

Looks like `RECALCULATION_SUCCESS` before data actually written into DB

and COHORT_FETCH_SUCCESS gives outdated data

in cohortRecalculate.js
```javascript
    .catch(err => console.error(err.message))
    .then(
      admin
        .database()
        .ref(`/cohortRecalculateQueue/${cohortKey}/${taskKey}`)
        .remove()
    );
```
should be .then( () => admin.database...) instead of .then(admin.database...)
