### ISSUE TITLE
Course Progress as undefined and no submission

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#502]
For dev-site's courses is showing the following as Progress in instructor view:

![image](https://user-images.githubusercontent.com/26617036/46523375-1c5a0780-c8b8-11e8-8c95-909df80889ce.png)

![image](https://user-images.githubusercontent.com/26617036/46525214-9771ec80-c8bd-11e8-8470-132dc95a88f0.png)

The course participants have already submitted their solutions, but it is displaying no submission yet.
And the progress is as undefined.

**Comment by Brainenjii** [comment]
should be fixed in #501
