### ISSUE TITLE
Profile Update Name should be globally updated in the app (?)

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#508]
This is from a user:
> On dev, I changed my display name to K H. I went back to my cohort view and found my old profile name "Kevin Hitchhiker" still taking up space in the class listing. My K H didn’t ripple over.
-Kevin

For the display name on Profile page:
![image](https://user-images.githubusercontent.com/26617036/46572310-30842e80-c9b6-11e8-81f9-800bc7bdffba.png)

Currently do we update the display name for Course/Path/Cohort/Assignment as well? Is the update global?

**Comment by Brainenjii** [comment]
In class listing means list of courses/cohorts or at course's assignments?

**Comment by FeynmanDNA** [comment]
![image](https://user-images.githubusercontent.com/26617036/46642729-2d05c880-cbab-11e8-9bc5-64f9abd6e7a6.png)
for example like the instructor column for courses/cohorts

**Comment by FeynmanDNA** [comment]
![image](https://user-images.githubusercontent.com/26617036/46716456-a75f4700-cc96-11e8-8a5a-f8a2305418ea.png)

looks like if the cohort is public, the instructor will not be updated on cohorts page
this is a minor issue as very few cohorts will end up being public.

**Comment by FeynmanDNA** [comment]
Update on this issue, it seems that for courses, the instructor name is not updated, and these are all non-public courses:
![image](https://user-images.githubusercontent.com/26617036/46716704-a7137b80-cc97-11e8-8720-85abd46a23f9.png)

**Comment by Brainenjii** [comment]
oh, right. Once you made course or cohort as `public` then you can't change it directly. I think we should add rights to control published courses/cohorts to admins

**Comment by Brainenjii** [comment]
ok, I'm closing this issue. Feel free to reopen if you'll reproduce it. Note - you should be in `/admins` node to get rights to update published (cohorts|courses|paths)

**Comment by FeynmanDNA** [comment]
@Brainenjii thanks!
