### ISSUE TITLE
CodeCombat level path add to Path page but not showing unless refresh page

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#509]
When I add a CodeCombat Level Path to a Path page, the activity notification says the "problem is saved", but the added path activity is **not showing** on the Path page. I have to refresh the page for the activity to be displayed on the Path page.

Console is showing "activity undefined":
![image](https://user-images.githubusercontent.com/26617036/46591361-ce7a1500-caec-11e8-8cf3-a5d5da119931.png)

**Comment by FeynmanDNA** [comment]
hmm, strange. now the added path activity is updated in real-time to the page, and there is no need to refresh the page...

**Comment by Brainenjii** [comment]
List of activities at Path container handled by firebaseConnect. So, it should be refreshed with firebase live-update approach. It could take several seconds to apply. Mb problem in that delay?
