### ISSUE TITLE
Permission Denied when updating profile display name

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#525]
![image](https://user-images.githubusercontent.com/26617036/46716542-06bd5700-cc97-11e8-9572-0ed90c3b8d7b.png)

But when refreshed the page, the update is actually picked up by the database...

![image](https://user-images.githubusercontent.com/26617036/46716556-1b015400-cc97-11e8-9dda-7f50e35b0ddd.png)

**Comment by Brainenjii** [comment]
Should be fixed now. Same with #508

**Comment by Brainenjii** [comment]
ok, I'm closing this issue. Feel free to reopen if you'll reproduce it. Note - you should be in `/admins` node to get rights to update published (cohorts|courses|paths)
