### ISSUE TITLE
Game Passenger Pickup Game Blank Screen for game graphics

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#526]
When I first opened the game assignment, this is what i saw on the screen:
![image](https://user-images.githubusercontent.com/26617036/46723784-37a78700-ccab-11e8-987f-216c03a08cff.png)

I think you can reproduce the issue by refreshing the course page and reopen the game.

**Comment by walkwel** [comment]
Hi @FeynmanDNA 
I checked the issue & I found
This issue is only generated on the development server.
When I run this on my local server, It works fine.
Also one thing I found, when I resize the window screen, the game graphics loaded

**Comment by FeynmanDNA** [comment]
we are no longer supporting game/tournament components
