### ISSUE TITLE
Game Tournament Activity for Path UX

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#539]
**1.  When Click "SOLVE" for a tournament activity**
![image](https://user-images.githubusercontent.com/26617036/47058055-ec82fc00-d1f5-11e8-8f16-9ca68515f38a.png)

**2. It shows up a tournament table based on the default code in the game, and simulated with all the available levels of difficulties of bot. Click on each score in the tournament table's cell will bring up that individual match**
![image](https://user-images.githubusercontent.com/26617036/47057620-1804e700-d1f4-11e8-8ef6-5e6f6801bcfa.png)

**3. For example, user clicked "You vs Easy Bot (player 1 vs player 2)" in the table's cell, and now that match will be opened as a game activity will. Now user can edit the code in this game and try to win this match**
![image](https://user-images.githubusercontent.com/26617036/47058247-dcb7e780-d1f6-11e8-8a71-bc15a77b155d.png)

**4. After they are satisfied with the code for that match, they close the individual match modal window and back at the tournament table view. They can now click "RESIMULATE" to see how their updated code in the match perform in the whole tournament**
![image](https://user-images.githubusercontent.com/26617036/47057792-cdd03580-d1f4-11e8-9c64-8596e7842475.png)

**5. After resimulating the tournament, the updated code for that match in step 3 now make the user move up in the tournament table ranking. User can repeat step 2-4 to get their desired tournament table result. NOTE: once the tournament score to pass threshold is met, user can now "COMMIT" their tournament activity as complete.**
![image](https://user-images.githubusercontent.com/26617036/47057932-6c5c9680-d1f5-11e8-8216-c48a35f26cfe.png)

**6. After click "COMMIT" in the tournament view, user is now back at the Path page with a checked status for that tournament activity**
![image](https://user-images.githubusercontent.com/26617036/47058135-42f03a80-d1f6-11e8-8534-58c2b1527cfd.png)

**Comment by MKoth** [comment]
Hi, @walkwel , I've added PR to games repo, where I've added support for switching between tournament and game simulation, also, yours changes has been implimented. Just make sure you send gameType=gameTournament to props. Please, take a look!

**Comment by walkwel** [comment]
@FeynmanDNA I think there should be End button also on point no. 3 along with Restart and Pause/Resume

**Comment by FeynmanDNA** [comment]
we are no longer supporting game/tournament components
