### ISSUE TITLE
Course Assistant should be able to refresh course assignment

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#545]
![image](https://user-images.githubusercontent.com/26617036/47197956-1f66f480-d39c-11e8-9a4c-ec0706a1bc1b.png)
just like a course instructor

**Comment by Brainenjii** [comment]
Just checked - I'm able to see these buttons as instructor. Could you show ids of user and course?

**Comment by FeynmanDNA** [comment]
@Brainenjii I was viewing it in the wrong account. Thanks for pointing it out.
