### ISSUE TITLE
Make the Jupyter code editor adapt to the number of lines of code or be 40 lines by default. 

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#554]
![image](https://user-images.githubusercontent.com/26947311/47278102-c9db5380-d5f8-11e8-88ce-1980bfc4b9f2.png)

**Comment by Aishwarya26l** [comment]
Pull Request #688 
Fix - 
Minimum rows set to 20 and maximum to 40. 
Cases where content exceeds 40 lines, content becomes scrollable.
