### ISSUE TITLE
of and /

### ISSUE THREAD

**Issue by ngmhprogramming** [NUS-ALSET/achievements#576]
when you view a course, some people have their activities displayed as x of y while others have x / y

**Comment by FeynmanDNA** [comment]
@ngmhprogramming hi ngm, when users submit/update progress from their own session by "Update Path Progress", the activities will be displayed as "x of x".

When course instructors refresh the course page (from instructor view, there is a "Refresh" button), the activities will be displayed as "x/x".

In a way, this "bug" has allowed us to see how many users choose to update their path progress on their own :)
