### ISSUE TITLE
Built in python evaluator too strong

### ISSUE THREAD

**Issue by IngeniousCoder** [NUS-ALSET/achievements#581]
Hello,
I used this application for Ace of Coders 2018, and would like to give a feedback which I believe will help:
The ```os``` module is available for import through the python intepreter in the "PYTHON BASICS BY ALSET" Track .
I think that the os module should be blacklisted in the intepreter for the following reasons :
- OS is too strong. OS can be used to access private information, wipe the system, etc.

Please consider my feedback. Thanks.

**Comment by FeynmanDNA** [comment]
@IngeniousCoder Hi, thank you so much for your feedback! We have set up the system in such a way that you can use `os` module freely.

You can actually play around with the `os` modules as part of your solution and click "RUN" in our notebook activities. 

I have written a sample Python snippet you can use to see the results returned from our server:
```python
import os
import subprocess
import glob
import shutil

path = os.getcwd()

print("current path is ", path)

dirs = os.listdir(path)

print(len(dirs))

# list all the files/dirs in cwd
for file in dirs:
    print (file)
    
print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")

# if we wipe everything here:
for fs in glob.glob("*"):
    if os.path.isfile(fs):
        os.remove(fs) # remove file
    elif os.path.isdir(fs):
        shutil.rmtree(fs)  # remove dir

dirs = os.listdir(path)

print(len(dirs))

for file in dirs:
    print (file)
print("HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH")

# change to root directory
os.chdir('/')

path = os.getcwd()

print("current path is ", path)

p1 = subprocess.Popen(['ls','-al'], stdout=subprocess.PIPE)
print(p1.communicate())

# if we wipe the root
for fs in glob.glob("*"):
    if os.path.isfile(fs):
        os.remove(fs) # remove file
    elif os.path.isdir(fs):
        shutil.rmtree(fs)  # remove dir
        
p2 = subprocess.Popen(['ls','-al'], stdout=subprocess.PIPE)
print(p2.communicate())
```

Our Python code is running inside the `/tmp` folder, and you will see that if we wipe the whole `/tmp` folder, the server can still handle incoming notebook submissions.

If we use `os` to wipe the system, we will get `PermissionError`. 

Hope it helps!
