### ISSUE TITLE
Make the cohort grid sortable by columns

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#585]
Clicking on column headers (Cours Rank, Explorers, Total Students, etc.) should sort the grid in a similar manner to the assignments grid in courses. The default sorting should continue to be explorers from largest to smallest values. 

![screen shot 2018-10-31 at 12 56 47 pm](https://user-images.githubusercontent.com/26947311/47766983-7cec3100-dd0c-11e8-9eef-86e27b553c11.png)

**Comment by Brainenjii** [comment]
sorry for delay, it was fixed already, I just didn't commit and PR
