### ISSUE TITLE
The read only text in the Jest editor is missing a space. 

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#596]
At a minimum, a space should be added between the read only text and the file name. Ideally, there should be a more visual way to communicate which files are read only and which can be edited. 

![image](https://user-images.githubusercontent.com/26947311/48186978-a47a7380-e374-11e8-9403-5c2a3c0e64fa.png)

**Comment by Aishwarya26l** [comment]
Pull Request: https://github.com/NUS-ALSET/achievements/pull/688
Fix -
<img width="256" alt="screenshot 2019-01-15 at 9 45 21 pm" src="https://user-images.githubusercontent.com/33215672/51184325-ec86bb00-190e-11e9-8aa8-02c69f58afb6.png">
