### ISSUE TITLE
fucionChart is creating 2MB bundle

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#655]
![image](https://user-images.githubusercontent.com/26617036/50431578-e18bcc80-0906-11e9-9bad-c89839f9a868.png)

**Comment by Brainenjii** [comment]
We could split this chart from the main bundle in the same manner as AceEditor - https://github.com/NUS-ALSET/achievements/blob/5506185d856f0f00e157dd878e0bbbd79a3c475b/src/components/activityViews/JupyterNotebook.js#L29

**Comment by FeynmanDNA** [comment]
@Brainenjii thanks for the advice. I am working on a PR to implement the code-splitting

**Comment by FeynmanDNA** [comment]
![image](https://user-images.githubusercontent.com/26617036/50432313-ec952b80-090b-11e9-8a16-ff43fb58f4c8.png)
