### ISSUE TITLE
Implement a detection for missing pathId, problemId, accountId, cohortId

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#691]
Currently if the site is going to a URL parameter involving accountId, problemId, pathId, assignmentId cohortId..., any Id that we use to connect to the Firebase database, if the Id does not exist in the backend, the page typically goes to a loading UI view. 

We need a defensive check for the existence of the Id before rendering the UI.

**Comment by scboesch** [comment]
We should tell the users that xxxxxId does not exist, rather than showing a continually loading page.
