### ISSUE TITLE
Python Code Analysis

### ISSUE THREAD

**Issue by Brainenjii** [NUS-ALSET/achievements#696]
Get all of the code a

- nalysis features working. We want to be able to call the code analysis function whenever people submit a passing Jupyter solution. Then we want to save the results that come back from the code analysis. 
- Here is the Code Analysis service that we will POST python code to in order to determine what python skills (features) users are using to solve problems. https://ltp7y8q1ak.execute-api.ap-southeast-1.amazonaws.com/default/code_analysis
- Here is the source code for this AWS Lambda function. https://github.com/NUS-ALSET/lambda-code-analysis

**Comment by Thangamanir** [comment]
Fixed. 
https://github.com/NUS-ALSET/achievements/pull/836
