### ISSUE TITLE
Export User Data Feature

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#720]
Provide users with a button on their profile page to allow users to download some of their Achievements data as a json file. 

This json file should contain the data from these initial locations that the user is allowed to edit. We will let users download this data to locally analyze their path solutions. 
userAchievements -> $userKey
users -> $userKey
usersPrivate -> $userKey
completedActivities -> $userKey  (Contains $pathKey’s and $activityKey’s)
problemSolutions" -> $activityKey -> $userKey (lookup by $activityKey)

**Comment by walkwel** [comment]
PR #728 Fixes this issue
