### ISSUE TITLE
Extend the CodeCombat multiplayer level activity assignment to show the user’s rank

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#723]
Extend the CodeCombat multiplayer level activity assignment to show the user’s rank in the ladder rather than just showing COMPLETE on the instructor’s view tab. If solutions are public, show the user’s rank in the assignment tab as well.

The assignment column should be sortable by rank. 

![image](https://user-images.githubusercontent.com/26947311/52932127-c75fef00-3389-11e9-935b-4afa187f26d8.png)

**Comment by walkwel** [comment]
PR #733 fixes this issue
