### ISSUE TITLE
Path Analytics

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#729]
Provide a graph to demonstrate how far along a path users are progressing after solving the first activity. 
Allow the data to be filtered to only show users starting the path after some datetime. 
Provide a way to compare two groups of users by showing users that started after one date compared to starting after another datetime. 

![image](https://user-images.githubusercontent.com/26947311/53152720-4d31a380-35f1-11e9-88c4-f9c5375ab9fc.png)

**Comment by walkwel** [comment]
@scboesch What x and y-axis will represent?

**Comment by scboesch** [comment]
The x-axis is the number of activities that have been completed. 
The y-axis is the percentage of users that have completed 1-activity and gone on to complete n-activities. x=1 will always be y=100%.

**Comment by walkwel** [comment]
@scboesch  Do I need to use student's solution data to find out the completed activities and their time. OR Do I need to use analytics/activityAttempts ?

**Comment by scboesch** [comment]
I believe that all the data should be in the analytics/activityAttempts node. We should be able to filter by pathKey and focus on the events where completed=1.  

Each of these charts is for a specific pathKey. 

The different color lines would be grouping users by the date that they solved the first activity on the path. "All Time" would be all users no matter when they completed the first activity on a path. "Since X weeks ago" could mean all users that solved the first activity within the last n weeks. 

We could let path owners adjust the time windows shown by each of these lines. For now, we and just hard code the lines to the 4 options shown (All time, 3 weeks, 2 weeks, 1 week)
