### ISSUE TITLE
CodeCombat level activities should have a solve button rather than a fetch button

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#748]
For some reason, CodeCombat level activities have a "FETCH" button rather than a "SOLVE" button in the path view. All activities, including CodeCombat activities should have a "SOLVE" button.  

![image](https://user-images.githubusercontent.com/26947311/53676841-ee4fe680-3ce2-11e9-9816-ddd8153bce61.png)
![image](https://user-images.githubusercontent.com/26947311/53676850-0162b680-3ce3-11e9-9189-c1902f7ed931.png)

**Comment by Aishwarya26l** [comment]
Changed CodeCombat Activities to have SOLVE buttons instead of FETCH buttons.

![image](https://user-images.githubusercontent.com/33215672/54729801-762d6000-4bc0-11e9-8d89-7ca4a0c5d6f3.png)
