### ISSUE TITLE
Path Solutions Review (Jupyter) 

### ISSUE THREAD

**Issue by Thangamanir** [NUS-ALSET/achievements#841]
Provide a way for path creators to page through the last few solutions submitted for Jupyter activities. Provide a way to show a read-only code editor (so that there is highlighting)  with the code from the code block the learner was allowed to edit. Only the submitted code needs to be shown.

**Comment by Thangamanir** [comment]
Unable to view the individual solutions. Also prefer to show userid instead of the User name.

**Comment by walkwel** [comment]
@Thangamanir can you please share the error or the video of the problem you are having in viewing the individual solution. Below is a video link, which shows the functionality working correctly in development environment. 
https://drive.google.com/file/d/1vsjWBKoICLyLqZx3wRTSGwO661eYQXE3/view
