### ISSUE TITLE
Unable to solve Code Combat activities 

### ISSUE THREAD

**Issue by Thangamanir** [NUS-ALSET/achievements#858]
Message "Profile Refresh Timeout" is displayed while trying to solve code combat activities.

**Comment by Brainenjii** [comment]
Could you provide link to broken path and activity? It works fine on https://achievements-dev.firebaseapp.com/#/paths/-L9JVgROKkDUhZs08WWp
Mb there was issue at CodeCombat side?

**Comment by Thangamanir** [comment]
> Could you provide link to broken path and activity? It works fine on https://achievements-dev.firebaseapp.com/#/paths/-L9JVgROKkDUhZs08WWp
> Mb there was issue at CodeCombat side?

This happens in production environment only
https://achievements-prod.firebaseapp.com/#/paths/-LJML2MVPrTOWQWyPHOd
is the path link. For all the activities.

**Comment by Brainenjii** [comment]
Oh, it's at prod. Could you check. Unfortunately, I have no access to the prod database. Could you check 
https://console.firebase.google.com/project/achievements-dev/database/achievements-dev/data/thirdPartyServices
and compare it with 
https://console.firebase.google.com/project/achievements-prod/database/achievements-dev/data/thirdPartyServices
I think it could contain non-full codecombat service info.
