### ISSUE TITLE
Public and Private Jupyter Data Files

### ISSUE THREAD

**Issue by Thangamanir** [NUS-ALSET/achievements#899]
Allow Jupyter notebook problems to include public data . This data will be included in the notebook execution environment since the execution environment will not have network access in the future. This test data will be over-writeable when private tests are available and the objective is to now provide users with access to the private data or feedback on how the private data is causing failures. We could show public test results and keep private notebook results secret by only showing the results of an output file shock can not leak private test information.

**Comment by Aishwarya26l** [comment]
On delete of public data from an existing activity -
1. [TODO] Remove file from the UI. 
2. [DONE] Remove file and its contents on firebase
