### ISSUE TITLE
75 Assignment submission status tracking. 

### ISSUE THREAD

**Issue by scboesch** [NUS-ALSET/achievements#91]
In the column headers for assignments, besides the details link, show the percentage of students who have completed the assignment. 

Submit your answer
[details](http://google.com) (75%)

**Comment by Brainenjii** [comment]
So, we should replace `3/4` to `75%`, right?

**Comment by scboesch** [comment]
I missed that we had implemented the 3/4 tracking. Let's stay with that for a while and see how it works. I will close this issue and re-open if we decide to move to percentage tracking.
